# Generated by Django 5.2.5 on 2025-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0005_alter_cartitem_cart_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
