# Generated by Django 5.2.5 on 2025-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
